### ISSUE TITLE
Load More / Infinite Scroll for Product Grid [JetWooBuilder]

### ISSUE THREAD

**Issue by thorsolutions** [CrocoBlock/suggestions#2683]
The only option for the Shop Page is pagination, since load more and infinite scroll options are available for stuff like Listing Grid, if this was there for Products Grid then it would be brilliant.

**Comment by stasonua0** [comment]
+1

**Comment by KHRifat** [comment]
+1

**Comment by tizum** [comment]
+1

**Comment by fabi20x** [comment]
+1 for products loop!

**Comment by marcsavall** [comment]
- Good product, but strange, I don't see any option for pagination ? I can choose the number of product but no pagination and no ajax loading ? I use XStore theme. 
- It could be nice to limit Titles to X characters and not to X Words.

**Comment by UraraReika** [comment]
> * Good product, but strange, I don't see any option for pagination ? I can choose the number of product but no pagination and no ajax loading ? I use XStore theme.

For pagination you can use combination with JetSmartFilter.

> * It could be nice to limit Titles to X characters and not to X Words.

https://prnt.sc/104tztt you can do it.

**Comment by P-happiness** [comment]
+1

**Comment by creativeart** [comment]
+1

**Comment by UraraReika** [comment]
In 1.7.5 version of JetWooBuilder we added compatibility between Archive & Categories items widget and JetEngine Listing. So right now you can build product card with the help of JetEngine listing and output it with listing grid widget which has load more option.

**Comment by stasonua0** [comment]
There is only one problem left to solve, this is the display of products or categories or categories + products in the archive, depending on the WooCommerce settings. At the moment, Jet engine listings cannot do this and this is their only drawback compared to Jet woo builder

/*Update*/
Realized that this version is not yet available for download

осталось решить всего одну проблему, это отображение в архиве товаров или категорий или категорий + товаров, в зависимости насроек WooCommerce. На данный момент листинги Jet engine этого не умеют и это единственный их минус по сравнению с Jet woo builder

**Comment by P-happiness** [comment]
> In 1.7.5 version of JetWooBuilder we added compatibility between Archive & Categories items widget and JetEngine Listing. So right now you can build product card with the help of JetEngine listing and output it with listing grid widget which has load more option.

Unfortunately I do not have JetEngine yet, so I can't try Listing Grid..
So my (stupid) question is:
Are you suggesting to use Jet Engine and Listing Grid to build a WooCommerce Shop instead of using JetWooBuilder widgets? 
I mean, is it possible to create a JetWoo Template (Shop) using Listing Grid instead of Product Grid widget?

If so, here it comes my second (stupid) question:
Shouldn't be easier to add a Load More button to JetWooBuilder Product Grid?
I'm sorry if I wrote something wrong. I'm not a developer.
I'm just trying to understand how to replace the Pagination with a Load More button (or Infinite Scroll) to my JetWoo Shop Template. 
Thanks!

**Comment by stasonua0** [comment]
Recommend using this plugin for Jet Woo Builder https://ru.wordpress.org/plugins/load-more-products-for-woocommerce/

**Comment by P-happiness** [comment]
> Recommend using this plugin for Jet Woo Builder https://ru.wordpress.org/plugins/load-more-products-for-woocommerce/

Thanks!
Did you already test this plugin with Product Grid?

**Comment by stasonua0** [comment]
Yes

**Comment by stasonua0** [comment]
> > Recommend using this plugin for Jet Woo Builder https://ru.wordpress.org/plugins/load-more-products-for-woocommerce/
> 
> Thanks!
> Did you already test this plugin with Product Grid?

Yes

**Comment by Hans-101** [comment]
+1

**Comment by P-happiness** [comment]
> > > Recommend using this plugin for Jet Woo Builder https://ru.wordpress.org/plugins/load-more-products-for-woocommerce/
> > 
> > 
> > Thanks!
> > Did you already test this plugin with Product Grid?
> 
> Yes

Hi Dear,
I'm trying to configure BeRocket, but I can't figure out how it works...
May I ask you something?
1) Do you have a free version or the pro version? Is the free version sufficient for the load more button functionality?
2) Do you have products pagination (jetwoobuilder) below products grid or you have deleted it? (I left the products pagination below the products grids.)
3) How did you set up the section "Selectors"? This part It's kind of confusing to me...
I'm scared to run the "Auto-Selectors" because it says "It will generate some products on your site. Please disable all SEO plugins and plugins, that doing anything on product creating."

Thanks

**Comment by ridiclo** [comment]
I am also getting stuck on Selectors. Auto-Selectors did not work well for me. I've been doing trial & error...

The scroll repeats the same products I had before and no new is being displayed.

**Comment by stasonua0** [comment]
> I am also getting stuck on Selectors. Auto-Selectors did not work well for me. I've been doing trial & error...
> 
> The scroll repeats the same products I had before and no new is being displayed.

is there pagination?

**Comment by ridiclo** [comment]
Yes, I have set up pagination, it works well. 
Here's my site: https://avessa.media/shop/

**Comment by ridiclo** [comment]
I guess the Load More plug-in hides/removes pagination once set up.

**Comment by nitsantbndt** [comment]
+1

**Comment by nitsantbndt** [comment]
> Recommend using this plugin for Jet Woo Builder https://ru.wordpress.org/plugins/load-more-products-for-woocommerce/

Any further insturction on this please? just a plain install and activation? or need some extra coding and hooks ?

**Comment by P-happiness** [comment]
> > Recommend using this plugin for Jet Woo Builder https://ru.wordpress.org/plugins/load-more-products-for-woocommerce/
> 
> Any further insturction on this please? just a plain install and activation? or need some extra coding and hooks ?

+1 

I tried to install the free version but nothing happened...
I'm getting stuck on "Selectors" and I don't know what to do...

If you guys want to share an Integration Guide with us, it would be very appreciated...
Thanks

**Comment by stasonua0** [comment]
https://www.loom.com/share/34c1ae4b191c40568df702b9f6d8a41a

**Comment by nitsantbndt** [comment]
> https://www.loom.com/share/34c1ae4b191c40568df702b9f6d8a41a

Thanks

**Comment by P-happiness** [comment]
> https://www.loom.com/share/34c1ae4b191c40568df702b9f6d8a41a

Thanks,
I tried, but for some reason it doesn't work to me...

I think the problem is on the filed : "Pagination Selector".
Tell me if I'm wrong.
I used Chrome Developer Tools (in my shop page) in order to get the selector from the jet woobuilder product pagination:
I have something like this: div.elementor-element.elementor-element-e6ca484.elementor-widget.elementor-widget-jet-woo-builder-products-pagination.is-mac

(I tried both with .is-mac extension  and without).
For the others selectors I've used the same values as yours.
I also used the responsive mode in order to hide the jet woo builder product pagination.
The only difference is that I do not have Product description widget under product Pagination.

Do you have any idea of what I'm doing wrong?
Thanks

**Comment by stasonua0** [comment]
I was doing automatic selection of selectors

**Comment by P-happiness** [comment]
> I was doing automatic selection of selectors

Thanks!

It' cuorios because I have different values from yours after the automatic selection...
I also had to put manually selectors for Next and Previous Page, because it didn't find values to put in there...
In fact, I copied your values.
So, now it works (meaning that at least now I can see the load more button), but the problem is that it repeat the same products...
I have:
Products Container Selector: div.jet-woo-products
Product Item Selector: div.jet-woo-products__item.jet-woo-builder-product
Pagination Selector: div.swiper-pagination
Next Page Selector: a.next.page-numbers
Previous Page Selector: a.prev.page-numbers

If you have any suggestion it would be very helpful to me!
And I'm very sorry if I'm bother you.
I'm going also to ask to their support if they can help me.
Thanks again!

**Comment by P-happiness** [comment]
> I was doing automatic selection of selectors

Actually I must correct me...
I just realized that it repeat the same products only on a JetWoo Custom Template...

On the main Jet Woobuilder Shop Template it works fine.
But I also have a Custom Shop Template for Tags (made using Jet Woobuilder Shop Template) and in there it repeat the same products.

Do you have any Custom Template (Category or Tags) in order to check it out?
Thanks!

**Comment by coversil** [comment]
> I was doing automatic selection of selectors

 Were you able to work with jet filter or any other ajax filter?
When I use the filter and then scroll down it reloads all the products :(

**Comment by shopakr** [comment]
I purchased JetPlugins to develop custom Product Archives and Shop Templates. And I also feel that JetWooBuilder should offer a LoadMore feature. Almost all well built sites with a lot of products are using the LoadMore or Infinite Scroll Feature. Why only offer it for Listing Grid. But I need the Load More Feature to work with the Product Loop not just the Products Grid, since my e-commerce templates are created using the Product Loop Widget from JetWooBuilder. Trying to reduce the number of Plugins I need to use so it would be really great if you offered this feature.

**Comment by Lucycontigo** [comment]
Still impossible to add infinite srocll to grid products template?
I have made the product template with the listing jet engine, but it has been impossible for me to place it dynamically as they come by presentation in products grid.
please help!!!

**Comment by Theo789595** [comment]
I am trying to make load more work too and i still struggle. I tried using the BeRocket load more plugin, it worked (you can make it work only if you display products list using woocommerce shortcode) but when i filter products using jetsmartfilters the load more button disappears so it is basically incompatible with crocoblock. 

It sounds like a really usefull function to add load more button in jetwoobuilder for products (working on product widgets and plain woocommerce shortcode).

Feels like demand for this is quite high. Many people need this.

**Comment by UraraReika** [comment]
You can check this [page](https://crocoblock.com/freemium/tools/) for additional plugin or download directly from [repo](https://github.com/UraraReika/jwb-products-grid-load-more).

**Comment by marcofrasson** [comment]
@UraraReika Hi! It works much less when using JetWooBuilder's quantity field with the OceanWP theme. Theme adds plus and minus buttons, but when loading the infinite scroll, the buttons don't appear. Do you know how to fix this?

**Comment by marcofrasson** [comment]
Another important point, if I use JetSearch for search or any search, the second page results go wrong. See this link that when searching the term "makeup", it correctly shows the first page, but the next products do not https://vitrinedamadeira.goflow.digital/?s=maquiagem&jet_ajax_search_settings=%7B%22search_source%22%3A%22product%22 %2C%22search_taxonomy%22%3A%22product_cat%22%2C%22results_order_by%22%3A%22relevance%22%2C%22results_order%22%3A%22asc%22%7D&post_type=product&jet_ajax_search_categories=0

And see in this link also the error of the buttons of the quantity field that I mentioned.

**Comment by UraraReika** [comment]
Hello @marcofrasson ! 

Please create separate issue for this here or in the plugin repo.
I know how to fix this quantity. button issue. As for second problem we still and some compatibility so this will fixed in one of the next update of plugin.

**Comment by marcofrasson** [comment]
Okay, thanks for the answer. How will I know when it was updated, as these two features are essential for us.

**Comment by UraraReika** [comment]
> Okay, thanks for the answer. How will I know when it was updated, as these two features are essential for us.

Keep an eye on JetWooBuilder Products Grid Load More updates.

**Comment by bean4896** [comment]
I downloaded the extension from https://crocoblock.com/freemium/tools/ . But the load more only can be loaded once

**Comment by wildmercury** [comment]
This 'JetWooBuilder Products Grid Load More' plugin (https://crocoblock.com/knowledge-base/articles/jetwoobuilder-devtools-products-grid-load-more-addon/) only seems to work on a plain vanilla Product Grid widget. It does not appear to function with a Products Loop widget, with or without the layout switcher, so it doesn't really solve anything but the most simple grid arrangement for any woocommerce shop.

**Comment by jivaneo** [comment]
Hi,
We need that feature on Product archives with Loops, definitely!

**Comment by ricardoaraujo330** [comment]
+1
