### ISSUE TITLE
Make Jet Menu cache-friendly

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#4671]
JetMenu is an awesome menu system, but when caching is enabled (page level cache) it stops working with following error in a network request (usually after a day when nonce expires):

{code: "rest_cookie_invalid_nonce", message: "Cookie check failed", data: {status: 403}} code: "rest_cookie_invalid_nonce" data: {status: 403} message: "Cookie check failed"

Please allow it to be used also with page cache enabled

**Comment by rtpHarry** [comment]
In theory you should be able to enable ESI in your cache plugin (Edge Side Includes). LiteSpeed Cache supports it and it has a list of nonces which it auto wraps for you, including `wp_rest` which the public api in JetMenu uses.

However, I'm not seeming to have much success with this, as I thought it was solved but I've just found the cache has expired again and it's broken again.

Very difficult to test as well because it takes 24 hours for the nonce to expire before it happens again.

I don't know why it insists on using the api at all, in my opinion it should load it in as the markup on page load. 

If I recall, there is some setting in the JetMenu plugin options about using ajax or not but I don't think it does what it implies.

It's starting to look like I'm going to have to go through all the sites I've built and remove JetMenu, so I'm really hoping we can find a better solution.

**Comment by mixedupcynth** [comment]
I am having major caching issues with JetMenu as well. We use WPEngine for hosting and I cannot turn caching off there. It's making it very difficult to build and test; clearing the cache does not solve it. I have wasted several hours on this and still do not have a functional menu that I can use.

**Comment by Ryzodus-RB42** [comment]
Reproduced this on JetMenu 3.0.4 / WordPress 7.1 behind a 24h full-page cache, and I think the framing in this issue undersells how small the fix is on the plugin side.

**The nonce isn't needed on this endpoint.** `get-elementor-template-content` is already authorised by the `signature` parameter. It returns 200 with no `X-WP-Nonce` header at all. Replaying the exact failing request three ways:

| Request | Result |
|---|---|
| `X-WP-Nonce` from a 17h-old cached page | **403** `rest_cookie_invalid_nonce` |
| `X-WP-Nonce` from a fresh, cache-busted fetch | **200** + template content |
| **no nonce header at all** | **200** + template content |

So the request fails *only because* a stale nonce is present. Sending nothing works.

The 403 itself is core behaviour, not something JetMenu can catch: `rest_cookie_check_errors()` rejects any request presenting a nonce that doesn't verify, **regardless of whether the endpoint required authentication**. Confirmed against a stock route with no plugins involved — `/wp/v2/pages?per_page=1` returns 200 with a fresh nonce and 403 with a stale one.

Why caching triggers it: `nonce_life` defaults to 86400, but `wp_nonce_tick()` halves that, so minimum validity is ~12h. Any page cached longer than that serves a dead nonce. (Worth noting cache age doesn't bound nonce age — I saw a cached object carrying a nonce older than its own `Last-Modified`.)

The line, in `assets/public/js/jet-menu-public-scripts.js`:

```js
data: { id: t, dev: …devMode, signature: o },
beforeSend: function(e,t){ e.setRequestHeader("X-WP-Nonce", window.jetMenuPublicSettings.restNonce) }
```

Attaching the header only when there's actually a logged-in session would fix this for every cached site, without changing the authorisation model. I'd defer to you on whether logged-in previews/dev mode still need it.

**Site-side workaround** until then, for anyone else landing here: raise `nonce_life` for logged-out visitors only, so cached nonces outlive the cache.

```php
add_filter( 'nonce_life', function ( $life ) {
    return is_user_logged_in() ? $life : max( (int) $life, 3 * DAY_IN_SECONDS );
}, 9999 );
```

Two gotchas with that: use `max()` so you don't shorten a lifetime another plugin extended (Gravity Forms sets its own submission nonces to 3 days), and **purge immediately after deploying it** — changing `nonce_life` changes the tick size and invalidates every anonymous nonce already sitting in cache, so things get worse until you do.

Full write-up with the verification steps and what else broke on the same nonce (JetEngine shares the identical `restNonce`): https://www.ryzodus.com/logbook/jetmenu-mega-menu-rest-cookie-invalid-nonce/ — my own site, linked because the detail didn't fit here.
